#!/bin/sh
set -e

# script/test: Run the test suite for the application.

echo "==> Checking linting and formatting of the code"

bun run lint

echo "==> Typechecking the code"

bun run typecheck

echo "==> Compiling the assets"

bun run compile

echo "==> Running the unit tests"

bun run test:unit

echo "==> Installing browsers for the test suite"

bunx playwright install chromium

echo "==> Running the integration tests"

bun run test:integration:cli

