#!/bin/sh
set -e

# script/test: Run the test suite for the application.

echo "==> Linting the code"

echo "\x1b[1mLinter:\x1b[0m Biome
\x1b[1mCoverage:\x1b[0m JavaScript, TypeScript, JSX, TSX, JSON, CSS, GraphQL
\x1b[1mCoverage restricted by package.json script:\x1b[0m no
\x1b[1mCoverage last checked:\x1b[0m 18 October 2024"
bun run lint:biome

echo "\x1b[1mLinter:\x1b[0m Stylelint
\x1b[1mCoverage:\x1b[0m CSS
\x1b[1mCoverage restricted by package.json script:\x1b[0m yes
\x1b[1mCoverage last checked:\x1b[0m 18 October 2024"
bun run lint:stylelint

echo "==> Typechecking the code"

bun run typecheck

echo "==> Compiling the assets"

bun run compile

echo "==> Running the unit tests"

bun run test:unit

echo "==> Installing browsers for the test suite"

bunx playwright install chromium

echo "==> Running the integration tests"

bun run test:integration:cli
